spring.application.name=sansaweigh-app

# --- MongoDB ---
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=sansaweigh

# --- Redis (cliente Jedis) ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.client-type=jedis

# --- API externa de especificaciones de balanza (Mockoon) ---
external.scale.api.url=http://localhost:3000

# --- Actuator (health de Redis y Mongo) ---
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
